### ISSUE TITLE
bug: When generating docs for multi `entryPoints` the output JSON is incomplete

### ISSUE THREAD

**Issue by fponticelli** [RealShadowNova/typedoc-json-parser#256] opened 2024-07-12 17:01 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the bug

My project exports many files individually and doesn't have an `index.ts` file that re-exports. 

### Steps To Reproduce

When I generate the `api.json` with typedocs I can see that all the exports are captured. When I run `typedoc-json-parser` on top of it, the results is the following:

```
{
  "typeDocJsonParserVersion": "10.1.5",
  "id": 0,
  "name": "@tempots/std",
  "version": "0.10.7",
  "dependencies": {},
  "readme": "# Tempo Standard Library\n",
  "changelog": null,
  "classes": [],
  "enums": [],
  "functions": [],
  "interfaces": [],
  "namespaces": [],
  "typeAliases": [],
  "variables": []
}
```

### Expected behavior

I would expect for the types to be generrated.

**Comment by RealShadowNova** [comment] 2024-09-30 03:50
Duplicate of #107

**Comment by RealShadowNova** [comment] 2024-09-30 03:53
I apologize for only now seeing this. I have been on a break from coding for awhile now. I will investigate further to see what I can do to resolve this.

**Closed** 2024-09-30 04:17 UTC
Labels: bug:unverified

**Comment by fponticelli** [comment] 2024-09-30 04:37
Thank you for the fix!
